
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from './home.module.css';
import Navbar from '../componentes/navbar/navbar'
import { Footer } from "flowbite-react";
import { BsDribbble, BsFacebook, BsGithub, BsInstagram, BsTwitter } from "react-icons/bs";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<
  {children: React.ReactNode;}
  >) {

  return (
    <html lang="es">
      <body className={inter.className}>
        <div className={styles.banner}>
          <div className={styles.headerText}>
            <span className="text-bruViolet font-black">envios gratis</span>
            <span >con compras que superen los $10.000</span>
          </div>
        </div>
        <Navbar/>
        {children}
        {/*FOOTER*/}
        <Footer container className=" bg-bruViolet">
          <div className="w-full">
            <div className="grid w-full justify-between sm:flex sm:justify-between md:flex md:grid-cols-1">
              <div >
                <Footer.Brand
                  href="#"
                  src=""
                  alt="NexusTech"
                  name=""
                  className="text-white"
                />
              </div>
              <div className="grid grid-cols-2 gap-8 sm:mt-4 sm:grid-cols-3 sm:gap-6">
                <div>
                  <Footer.Title title="about"  className="text-white"/>
                  <Footer.LinkGroup col >
                    <Footer.Link href="#"  className="text-white">algo</Footer.Link>
                    <Footer.Link href="#"  className="text-white">algo2</Footer.Link>
                  </Footer.LinkGroup>
                </div>
                <div>
                  <Footer.Title title="Follow us"  className="text-white"/>
                  <Footer.LinkGroup col>
                    <Footer.Link href="#" className="text-white">Github</Footer.Link>
                    <Footer.Link href="#" className="text-white">Discord</Footer.Link>
                  </Footer.LinkGroup>
                </div>
                <div>
                  <Footer.Title title="Legal"  className="text-white" />
                  <Footer.LinkGroup col>
                    <Footer.Link href="#" className="text-white">Privacy Policy</Footer.Link>
                    <Footer.Link href="#" className="text-white">Terms &amp; Conditions</Footer.Link>
                  </Footer.LinkGroup>
                </div>
              </div>
            </div>
            <Footer.Divider />
            <div className="w-full sm:flex sm:items-center sm:justify-between">
              <Footer.Copyright href="#" by="Desgined by Juan Pablo Del Rosso" year={2024} className="text-white"/>
              <div className="mt-4 flex space-x-6 sm:mt-0 sm:justify-center ">
                <Footer.Icon href="#" icon={BsFacebook}  className="text-white"/>
                <Footer.Icon href="#" icon={BsInstagram}  className="text-white"/>
                <Footer.Icon href="#" icon={BsTwitter}  className="text-white"/>
                <Footer.Icon href="#" icon={BsGithub}  className="text-white"/>
                <Footer.Icon href="#" icon={BsDribbble}  className="text-white"/>
              </div>
            </div>
          </div>
        </Footer>
      </body>
    </html>
  );
}

